name: Yazilim Derleme

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Kodu indir
      uses: actions/checkout@v3

    - name: Arduino CLI kur
      uses: arduino/setup-arduino-cli@v1
      with:
        version: 0.35.3

    - name: ESP32 platformu ve kutuphaneleri yukle
      run: |
        arduino-cli core update-index
        arduino-cli core install esp32:esp32
        arduino-cli lib install "DallasTemperature"
        arduino-cli lib install "OneWire"

    - name: Kodu derle
      run: |
        mkdir -p build
        arduino-cli compile --fqbn esp32:esp32:esp32 . --build-path ./build

    - name: Cikti dosyasini kaydet
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: build/*.bin
